# Generated by Django 3.2 on 2021-05-15 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_auto_20210515_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='city',
        ),
        migrations.RemoveField(
            model_name='room',
            name='mainCenter',
        ),
        migrations.RemoveField(
            model_name='room',
            name='street',
        ),
    ]
