# Generated by Django 3.2 on 2021-05-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_auto_20210515_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
